# Generated by Django 5.2.12 on 2026-06-16 22:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(help_text='Ano do ciclo institucional (ex: 2026)', unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('titulo', models.CharField(help_text='Ex: Ciclo Anual de Gestão de Riscos 2026', max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('Ativo', 'Ativo / Em Execução'), ('Encerrado', 'Encerrado / Concluído')], default='Ativo', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_criados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
