# Generated by Django 5.2.12 on 2026-06-16 23:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0001_initial'),
        ('usuario', '0004_remove_usuario_unidade_usuario_unidade_ativa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamento',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.centro'),
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='ano',
            field=models.IntegerField(help_text='Ano do ciclo institucional (ex: 2026)', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddConstraint(
            model_name='planejamento',
            constraint=models.UniqueConstraint(fields=('ano', 'centro'), name='unique_ano_centro'),
        ),
    ]
