# Generated by Django 5.2.12 on 2026-06-17 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0002_planejamento_centro_alter_planejamento_ano_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planejamento',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.RemoveConstraint(
            model_name='planejamento',
            name='unique_ano_centro',
        ),
    ]
