# Generated by Django 5.2.12 on 2026-03-29 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=25)),
                ('tipo_risco', models.CharField(max_length=25)),
                ('risco_identificado', models.CharField(max_length=25)),
                ('probabilidade', models.IntegerField()),
                ('impacto', models.IntegerField()),
                ('nivel_risco', models.IntegerField()),
                ('eficacia_residual', models.IntegerField()),
                ('nivel_residual', models.IntegerField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
