# Generated by Django 5.2.12 on 2026-06-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('causas', models.CharField(blank=True, max_length=250, null=True)),
                ('irregularidades', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
