# Generated by Django 5.2.12 on 2026-05-28 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identificacao', '0001_initial'),
        ('risco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificacao',
            name='risco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risco.risco'),
        ),
    ]
