# Generated by Django 5.2.12 on 2026-06-03 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
        ('identificacao', '0002_initial'),
        ('risco', '0004_risco_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificacao',
            name='desafio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desafio.desafio'),
        ),
        migrations.AlterField(
            model_name='identificacao',
            name='risco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risco.risco'),
        ),
    ]
