# Generated by Django 5.2.12 on 2026-06-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_alter_categoria_descricao_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao_categoria',
            field=models.CharField(max_length=350),
        ),
    ]
