apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: gestor
type: Opaque
stringData:
  POSTGRES_PASSWORD: "1234"
  POSTGRES_USER: "postgres"
  DATABASE_URL: "postgres://postgres:1234@db:5432/gestor_db"