# Generated by Django 5.2.12 on 2026-04-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidade', models.FloatField()),
                ('impacto', models.IntegerField()),
                ('nivel_risco', models.IntegerField()),
                ('contexto', models.CharField(max_length=200)),
                ('classificacao', models.CharField(max_length=200)),
            ],
        ),
    ]
