# Generated by Django 5.2.12 on 2026-05-28 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=250)),
                ('acao', models.CharField(max_length=250)),
                ('responsavel', models.CharField(max_length=250)),
                ('prazo', models.DateField()),
                ('prob_residual', models.IntegerField()),
                ('impacto_residual', models.IntegerField()),
                ('indicadores', models.CharField(max_length=250)),
                ('risco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risco.risco')),
            ],
        ),
    ]
