# Generated by Django 5.2.12 on 2026-04-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfil_acesso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='setor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
