# Generated by Django 5.2.12 on 2026-06-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0003_alter_unidade_nome_centro_alter_unidade_nome_unidade'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidade.unidade'),
        ),
        migrations.DeleteModel(
            name='Unidade',
        ),
    ]
