# Generated by Django 5.2.12 on 2026-06-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_unidade_delete_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil_acesso',
            field=models.CharField(choices=[('Admin', 'Administrador'), ('Gestor', 'Gestor de Riscos'), ('Auditor', 'Auditor')], default='Gestor', max_length=20),
        ),
    ]
