# Generated by Django 5.2.12 on 2026-06-16 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0003_alter_unidade_nome_centro_alter_unidade_nome_unidade'),
        ('usuario', '0003_alter_usuario_perfil_acesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='unidade',
        ),
        migrations.AddField(
            model_name='usuario',
            name='unidade_ativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_ativos_unidade', to='unidade.unidade'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='unidades_permitidas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_permitidos_unidade', to='unidade.unidade'),
        ),
    ]
