# Generated by Django 5.2.12 on 2026-06-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_unidade_usuario_unidade_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
