# Generated by Django 5.2.12 on 2026-06-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_estruturado', models.CharField(blank=True, max_length=30, null=True)),
                ('nome_unidade', models.CharField(blank=True, max_length=150, null=True)),
                ('nome_centro', models.CharField(blank=True, max_length=100, null=True)),
                ('sigla_centro', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_unidade', models.CharField(blank=True, max_length=50, null=True)),
                ('situacao', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
