# Generated by Django 5.2.12 on 2026-06-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0002_popular_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='nome_centro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nome_unidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
