# Generated by Django 5.2.12 on 2026-05-28 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desafio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('categoria', models.CharField(blank=True, max_length=30, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=40, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('desafio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='desafio.desafio')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True)),
                ('risco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risco.risco')),
            ],
            options={
                'db_table': 'usuario_risco',
            },
        ),
    ]
