# Generated by Django 5.2.12 on 2026-04-15 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacao', '0001_initial'),
        ('desafio', '0001_initial'),
        ('identificacao', '0001_initial'),
        ('tratamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('categoria', models.CharField(blank=True, max_length=30, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=40, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.avaliacao')),
                ('desafio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='desafio.desafio')),
                ('identificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identificacao.identificacao')),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamento.tratamento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=50)),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True)),
                ('risco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risco.risco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_risco',
                'unique_together': {('usuario', 'risco')},
            },
        ),
    ]
