# Generated by Django 5.2.12 on 2026-06-16 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0001_initial'),
        ('risco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrisco',
            name='ciclo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='planejamento.planejamento'),
        ),
        migrations.AddField(
            model_name='risco',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planejamento.planejamento'),
        ),
    ]
