# Generated by Django 5.2.12 on 2026-06-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risco', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risco',
            name='categoria',
        ),
    ]
