# Generated by Django 5.2.12 on 2026-06-02 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('risco', '0003_remove_risco_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='risco',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria'),
        ),
    ]
