# Generated by Django 5.2.12 on 2026-06-03 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risco', '0004_risco_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risco',
            name='desafio',
        ),
    ]
